services:
  bot:
    environment:
      PYTHONUNBUFFERED: 1
    command: python -u bot/bot.py

    build: .
    container_name: discord-modrinth-bot
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped